import globals from "globals";
import js from "@eslint/js";
import stylistic from "@stylistic/eslint-plugin";
import vue from "eslint-plugin-vue";
import { defineConfigWithVueTs, vueTsConfigs } from "@vue/eslint-config-typescript";
import { globalIgnores } from "eslint/config";

const INDENT = 4;

export default defineConfigWithVueTs(
    globalIgnores([
        "coverage/**",
        "dist/**",
        "node_modules/**",
        "playwright-report/**",
        "test-results/**",
    ]),

    js.configs.recommended,
    vue.configs["flat/recommended-error"],
    vueTsConfigs.strictTypeChecked,
    vueTsConfigs.stylisticTypeChecked,
    stylistic.configs.recommended,

    {
        languageOptions: {
            ecmaVersion: "latest",
            globals: {
                ...globals.browser,
                ...globals.webextensions,
            },
            parserOptions: {
                extraFileExtensions: [".vue"],
                projectService: true,
                tsconfigRootDir: import.meta.dirname,
            },
            sourceType: "module",
        },
        linterOptions: {
            reportUnusedDisableDirectives: "error",
            reportUnusedInlineConfigs: "error",
        },
    },

    {
        name: "cachecontrol/typescript",
        rules: {
            "@typescript-eslint/consistent-type-exports": ["error", { fixMixedExportsWithInlineTypeSpecifier: false }],
            "@typescript-eslint/consistent-type-imports": [
                "error",
                {
                    disallowTypeAnnotations: true,
                    fixStyle: "separate-type-imports",
                    prefer: "type-imports",
                },
            ],
            "@typescript-eslint/default-param-last": "error",
            "@typescript-eslint/explicit-function-return-type": [
                "error",
                {
                    allowExpressions: false,
                    allowHigherOrderFunctions: true,
                    allowTypedFunctionExpressions: true,
                },
            ],
            "@typescript-eslint/explicit-member-accessibility": "error",
            "@typescript-eslint/explicit-module-boundary-types": "error",
            "@typescript-eslint/max-params": ["error", { max: 3 }],
            "@typescript-eslint/member-ordering": "error",
            "@typescript-eslint/method-signature-style": ["error", "property"],
            "@typescript-eslint/no-import-type-side-effects": "error",
            "@typescript-eslint/no-loop-func": "error",
            "@typescript-eslint/no-shadow": "error",
            "@typescript-eslint/no-unnecessary-qualifier": "error",
            "@typescript-eslint/no-unnecessary-type-conversion": "error",
            "@typescript-eslint/no-unsafe-type-assertion": "error",
            "@typescript-eslint/no-unused-vars": [
                "error",
                {
                    args: "all",
                    argsIgnorePattern: "^_",
                    caughtErrors: "all",
                    ignoreRestSiblings: false,
                    varsIgnorePattern: "^_",
                },
            ],
            "@typescript-eslint/no-useless-empty-export": "error",
            "@typescript-eslint/parameter-properties": "error",
            "@typescript-eslint/prefer-destructuring": "error",
            "@typescript-eslint/prefer-readonly": "error",
            "@typescript-eslint/promise-function-async": "error",
            "@typescript-eslint/require-array-sort-compare": ["error", { ignoreStringArrays: true }],
            "@typescript-eslint/restrict-template-expressions": [
                "error",
                {
                    allowBoolean: false,
                    allowNever: false,
                    allowNullish: false,
                    allowNumber: true,
                    allowRegExp: false,
                },
            ],
            "@typescript-eslint/return-await": ["error", "in-try-catch"],
            "@typescript-eslint/strict-boolean-expressions": [
                "error",
                {
                    allowAny: false,
                    allowNullableBoolean: false,
                    allowNullableNumber: false,
                    allowNullableObject: true,
                    allowNullableString: false,
                    allowNumber: false,
                    allowString: true,
                },
            ],
            "@typescript-eslint/switch-exhaustiveness-check": "error",
        },
    },

    {
        name: "cachecontrol/core",
        rules: {
            "array-callback-return": ["error", { allowImplicit: false, checkForEach: true }],
            complexity: ["error", 10],
            "consistent-return": "error",
            curly: ["error", "multi-line"],
            "default-case-last": "error",
            eqeqeq: ["error", "always"],
            "func-style": ["error", "declaration"],
            "grouped-accessor-pairs": ["error", "getBeforeSet"],
            "guard-for-in": "error",
            "id-length": ["error", { exceptions: ["_"], min: 2 }],
            "logical-assignment-operators": ["error", "always"],
            "max-depth": ["error", 3],
            "max-lines-per-function": ["error", 60],
            "max-nested-callbacks": ["error", 3],
            "new-cap": "error",
            "no-alert": "error",
            "no-await-in-loop": "error",
            "no-bitwise": "error",
            "no-caller": "error",
            "no-console": "error",
            "no-constant-binary-expression": "error",
            "no-constructor-return": "error",
            "no-continue": "error",
            "no-else-return": ["error", { allowElseIf: false }],
            "no-eval": "error",
            "no-extend-native": "error",
            "no-extra-label": "error",
            "no-inline-comments": "error",
            "no-iterator": "error",
            "no-label-var": "error",
            "no-labels": "error",
            "no-lone-blocks": "error",
            "no-lonely-if": "error",
            "no-multi-assign": "error",
            "no-multi-str": "error",
            "no-nested-ternary": "error",
            "no-new-func": "error",
            "no-new-wrappers": "error",
            "no-object-constructor": "error",
            "no-param-reassign": ["error", { props: true }],
            "no-plusplus": "error",
            "no-promise-executor-return": "error",
            "no-proto": "error",
            "no-return-assign": ["error", "always"],
            "no-script-url": "error",
            "no-self-compare": "error",
            "no-sequences": "error",
            "no-template-curly-in-string": "error",
            "no-undef-init": "error",
            "no-underscore-dangle": "error",
            "no-unmodified-loop-condition": "error",
            "no-unneeded-ternary": "error",
            "no-unreachable-loop": "error",
            "no-useless-call": "error",
            "no-useless-computed-key": "error",
            "no-useless-concat": "error",
            "no-useless-rename": "error",
            "no-useless-return": "error",
            "no-var": "error",
            "no-void": ["error", { allowAsStatement: true }],
            "object-shorthand": ["error", "always"],
            "operator-assignment": ["error", "always"],
            "prefer-arrow-callback": ["error", { allowNamedFunctions: false, allowUnboundThis: true }],
            "prefer-const": ["error", { destructuring: "all" }],
            "prefer-exponentiation-operator": "error",
            "prefer-numeric-literals": "error",
            "prefer-object-has-own": "error",
            "prefer-object-spread": "error",
            "prefer-regex-literals": ["error", { disallowRedundantWrapping: true }],
            "prefer-rest-params": "error",
            "prefer-spread": "error",
            "prefer-template": "error",
            radix: ["error", "always"],
            "require-atomic-updates": "error",
            "require-unicode-regexp": "error",
            "sort-imports": [
                "error",
                {
                    allowSeparatedGroups: true,
                    ignoreCase: false,
                    ignoreDeclarationSort: true,
                    ignoreMemberSort: false,
                },
            ],
            "sort-keys": ["error", "asc", { caseSensitive: false, natural: true }],
            "symbol-description": "error",
            "unicode-bom": ["error", "never"],
            yoda: ["error", "never"],
        },
    },

    {
        name: "cachecontrol/vue",
        rules: {
            "vue/attributes-order": "error",
            "vue/block-lang": ["error", { script: { lang: "ts" } }],
            "vue/block-order": ["error", { order: ["script", "template", "style"] }],
            "vue/block-tag-newline": "error",
            "vue/component-api-style": ["error", ["script-setup"]],
            "vue/component-name-in-template-casing": [
                "error",
                "PascalCase",
                {
                    globals: [
                        "Teleport",
                        "Transition",
                        "TransitionGroup",
                    ],
                    registeredComponentsOnly: false,
                },
            ],
            "vue/custom-event-name-casing": ["error", "camelCase"],
            "vue/define-emits-declaration": ["error", "type-literal"],
            "vue/define-macros-order": [
                "error",
                {
                    defineExposeLast: true,
                    order: [
                        "defineOptions",
                        "defineModel",
                        "defineProps",
                        "defineEmits",
                        "defineSlots",
                    ],
                },
            ],
            "vue/define-props-declaration": ["error", "type-based"],
            "vue/define-props-destructuring": "error",
            "vue/enforce-style-attribute": "error",
            "vue/first-attribute-linebreak": ["error", { multiline: "below", singleline: "ignore" }],
            "vue/html-button-has-type": "error",
            "vue/html-indent": ["error", INDENT],
            "vue/max-attributes-per-line": [
                "error",
                {
                    multiline: { max: 1 },
                    singleline: { max: Number.MAX_SAFE_INTEGER },
                },
            ],
            "vue/max-lines-per-block": ["error", { script: 200, template: 200 }],
            "vue/max-props": ["error", { maxProps: 7 }],
            "vue/multi-word-component-names": [
                "error",
                {
                    ignores: [
                        "Options",
                        "Popup",
                    ],
                },
            ],
            "vue/no-boolean-default": "error",
            "vue/no-duplicate-attr-inheritance": "error",
            "vue/no-empty-component-block": "error",
            "vue/no-implicit-coercion": "error",
            "vue/no-multiple-objects-in-class": "error",
            "vue/no-ref-object-reactivity-loss": "error",
            "vue/no-required-prop-with-default": "error",
            "vue/no-root-v-if": "error",
            "vue/no-setup-props-reactivity-loss": "error",
            "vue/no-static-inline-styles": "error",
            "vue/no-template-target-blank": "error",
            "vue/no-undef-components": ["error", { ignorePatterns: [] }],
            "vue/no-undef-properties": "error",
            "vue/no-unused-emit-declarations": "error",
            "vue/no-unused-properties": ["error", { groups: ["props", "computed"] }],
            "vue/no-unused-refs": "error",
            "vue/no-useless-mustaches": "error",
            "vue/no-useless-v-bind": "error",
            "vue/padding-line-between-blocks": ["error", "always"],
            "vue/prefer-define-options": "error",
            "vue/prefer-separate-static-class": "error",
            "vue/prefer-true-attribute-shorthand": ["error", "always"],
            "vue/prefer-use-template-ref": "error",
            "vue/require-default-prop": "off",
            "vue/require-explicit-slots": "error",
            "vue/require-macro-variable-name": "error",
            "vue/require-typed-ref": "error",
            "vue/singleline-html-element-content-newline": "off",
            "vue/v-for-delimiter-style": ["error", "in"],
            "vue/valid-define-options": "error",
        },
    },

    {
        name: "cachecontrol/stylistic",
        rules: {
            "@stylistic/array-bracket-newline": ["error", "consistent"],
            "@stylistic/array-element-newline": ["error", "consistent"],
            "@stylistic/arrow-parens": ["error", "as-needed"],
            "@stylistic/brace-style": ["error", "1tbs", { allowSingleLine: false }],
            "@stylistic/comma-dangle": ["error", "always-multiline"],
            "@stylistic/eol-last": ["error", "always"],
            "@stylistic/function-call-argument-newline": ["error", "consistent"],
            "@stylistic/function-paren-newline": ["error", "consistent"],
            "@stylistic/indent": ["error", INDENT, { SwitchCase: 1 }],
            "@stylistic/indent-binary-ops": ["error", INDENT],
            "@stylistic/linebreak-style": ["error", "unix"],
            "@stylistic/max-statements-per-line": ["error", { max: 1 }],
            "@stylistic/member-delimiter-style": [
                "error",
                {
                    multiline: { delimiter: "semi", requireLast: true },
                    singleline: { delimiter: "semi", requireLast: false },
                },
            ],
            "@stylistic/multiline-ternary": ["error", "always-multiline"],
            "@stylistic/no-multiple-empty-lines": [
                "error",
                {
                    max: 1,
                    maxBOF: 0,
                    maxEOF: 0,
                },
            ],
            "@stylistic/no-trailing-spaces": "error",
            "@stylistic/nonblock-statement-body-position": ["error", "beside"],
            "@stylistic/object-curly-newline": ["error", { consistent: true, multiline: true }],
            "@stylistic/object-property-newline": ["error", { allowAllPropertiesOnSameLine: true }],
            "@stylistic/operator-linebreak": ["error", "before"],
            "@stylistic/padded-blocks": ["error", "never"],
            "@stylistic/padding-line-between-statements": [
                "error",
                { blankLine: "always", next: "return", prev: "*" },
                { blankLine: "any", next: "return", prev: "if" },
                { blankLine: "always", next: "*", prev: ["const", "let"] },
                { blankLine: "any", next: ["const", "let"], prev: ["const", "let"] },
                { blankLine: "always", next: "*", prev: "directive" },
                { blankLine: "any", next: "directive", prev: "directive" },
            ],
            "@stylistic/quote-props": ["error", "as-needed"],
            "@stylistic/quotes": ["error", "double", { avoidEscape: true }],
            "@stylistic/semi": ["error", "always"],
            "@stylistic/space-before-function-paren": [
                "error",
                {
                    anonymous: "always",
                    asyncArrow: "always",
                    named: "never",
                },
            ],
            "@stylistic/spaced-comment": ["error", "always", { markers: ["/"] }],
        },
    },

    {
        files: ["**/*.vue"],
        name: "cachecontrol/vue-indent",
        rules: {
            "@stylistic/indent": "off",
            "vue/script-indent": [
                "error",
                INDENT,
                {
                    baseIndent: 0,
                    switchCase: 1,
                },
            ],
        },
    },

    {
        files: [
            "eslint.config.ts",
            "vite.config.ts",
        ],
        name: "cachecontrol/config-files",
        rules: {
            "@typescript-eslint/explicit-module-boundary-types": "off",
        },
    },

    {
        files: [
            "e2e/**/*.ts",
            "test/**/*.ts",
        ],
        name: "cachecontrol/tests",
        rules: {
            "@typescript-eslint/max-params": "off",
            "@typescript-eslint/no-unsafe-type-assertion": "off",
            "max-lines-per-function": "off",
            "max-nested-callbacks": "off",
            "no-await-in-loop": "off",
        },
    },
);
